export default [
  {
    name: "Varşova Teknoloji Üniversitesi",
    img: "/assets/uni/varsova-teknoloji-universitesi.png",
    city: "Varşova",
    desc: "Varşova Teknoloji Üniversitesi, Polonya’daki teknik üniversiteler arasında en yüksek sıralamaya sahiptir ve uluslararası alanda da tanınmaktadır.",
    all_programs: [
      "Mimarlık",
      "Otomotiv ve İnşaat Makinaları Mühendisliği",
      "Çevre Mühendisliği",
      "İnşaat Mühendisliği",
      "Elektrik Mühendisliği",
      "Bilgisayar Bilimleri (IT)",
      "Mekatronik",
      "Uzay Mühendisliği",
      "Bina Hizmetleri, Hidro ve Çevre Mühendisliği",
      "Kimya ve Proses Mühendisliği",
      "Biyoteknoloji",
      "Telekomünikasyon",
      "Jeodezi ve Kartografi",
    ],
    data: {
      city: "Varşova",
      world_rank: "51-100",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://eng.pw.edu.pl/",
  },
  {
    name: "Kozminski Üniversitesi",
    img: "/assets/uni/kozminski-universitesi.jpg",
    city: "Varşova",
    desc: "1993 yılında kurulan Kozminski Üniversitesi, tam akademik haklara sahip özel bir yüksek öğretim kurumudur.",
    all_programs: ["Yönetim Ve Yapay Zeka", "Finansal Yönetim", "Yönetim"],
    data: {
      city: "Varşova",
      world_rank: "451-500",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://www.kozminski.edu.pl/en",
  },
  {
    name: "Collegium Humanum Üniversitesi",
    img: "/assets/uni/collegium-humanum-universitesi.jpg",
    city: "Varşova",
    desc: "Collegium Humanum Üniversitesi, 1995 yılında kurulmuş olup Polonya'daki en eski özel kolejlerden biridir.",
    all_programs: ["Yönetim Ve Yapay Zeka", "Finansal Yönetim", "Yönetim"],
    data: {
      city: "Varşova",
      world_rank: "-",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://humanum.pl/en/homepage/",
  },
  {
    name: "Polonya-Japonya Bilgi Teknolojileri Enstitüsü",
    img: "/assets/uni/polska-japanska-universitesi.png",
    city: "Varşova",
    desc: "İşverenler ve öğrenciler tarafından övgüyle karşılanan, Polonya'daki en iyi devlet dışı yüksek öğrenim kurumlarından biridir. ",
    all_programs: [
      "Bilgisayar Bilimleri (IT)",
      "Bilgi Yönetimi",
      "Grafik Tasarımı",
    ],
    data: {
      city: "Varşova",
      world_rank: "-",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://pja.edu.pl/",
  },
  {
    name: "SWPS Üniversitesi",
    img: "/assets/uni/swps-universitesi.png",
    city: "Varşova",
    desc: "Polonya'da Psikoloji ve Kültürel Çalışmalar ve Hukuk alanlarında doktora derecesi verme hakkına sahip tek özel üniversitedir.",
    all_programs: [
      "Bilgisayar Bilimleri (IT)",
      "Psikoloji",
      "Klinik Psikoloji",
      "Organizasyon Davranışı",
      "İnsan Kaynakları Yönetimi",
      "Uluslararası İş ve Yönetim",
      "Pazarlama ve İletişim",
      "Medya ve İletişim Çalışmaları",
      "Uluslararası İlişkiler ve Avrupa Çalışmaları",
      "Sosyoloji",
      "Cinsiyet Çalışmaları",
      "Politika Bilimi",
      "Hukuk",
      "Karşılaştırmalı Edebiyat",
      "Yaratıcı Yazma",
      "Hayvan Fizyolojisi",
    ],
    data: {
      city: "Varşova",
      world_rank: "-",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://swps.pl/oferta/warszawa",
  },
  {
    name: "Varşova Üniversitesi",
    img: "/assets/uni/varsova-universitesi.png",
    city: "Varşova",
    desc: "Polonya'nın en büyük üniversitesidir ve dünyanın en iyi üniversiteleri arasında ilk %3 arasında yer alan Polonya'nın önde gelen araştırma merkezlerinden biridir.",
    all_programs: [
      "Veri Bilimi ve İş Analitiği",
      "İngilizce Hazırlık",
      "AB Enerji ve İklim Hukuku",
      "Avrupa Siyaseti ve Ekonomisi",
      "Finans, Uluslararası Yatırım ve Muhasebe",
    ],
    data: {
      city: "Varşova",
      world_rank: "262 ",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://en.uw.edu.pl/",
  },
  {
    name: "SGH Üniversitesi",
    img: "/assets/uni/sgh-universitesi.jpg",
    city: "Varşova",
    desc: "Polonya'daki en eski ekonomi üniversitesidir ve Avrupa'nın önde gelen ekonomi üniversitelerinden biridir.",
    all_programs: [
      "Muhasebe ve Finansman",
      "İşletme Yönetimi",
      "Ekonomi ve Yönetim",
      "Uluslararası İlişkiler, Politika Bilimi ve Avrupa Çalışmaları",
      "Turizm Yönetimi",
      "İş ve Ekonomi İçin Nicel Yöntemler",
      "Dijital Ekonomide Ekonomi ve Yönetim",
    ],
    data: {
      city: "Varşova",
      world_rank: "301-350",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://www.sgh.waw.pl/en",
  },
  {
    name: "Varşova Yaşam Bilimleri Üniversitesi",
    img: "/assets/uni/varsova-yasam-bilimleri-universitesi.png",
    city: "Varşova",
    desc: "Üniversitede araştırma 16 enstitü tarafından yürütülmekte ve öğretim 13 fakülte tarafından sağlanmaktadır.",
    all_programs: [
      "Biyoteknoloji",
      "Organik Tarım ve Gıda Üretimi",
      "Gıda Bilimi: Teknoloji ve Beslenme",
      "Yönetim",
      "Uluslararası İlişkiler",
      "Ekonomi",
      "Bilgisayar Bilimi",
      "Veteriner Hekimlik",
      "Peyzaj Mimarlığı",
      "Turizm ve Rekreasyon Yönetimi",
      "Diyetetik ve İnsan Beslenmesi",
      "Çevre Mühendisliği",
      "Su Yönetimi ve Hidrolik Mühendislik",
      "Tarımsal Mühendislik",
      "Agrobiyoteknoloji",
      "Hayvan Bilimi",
      "Orman Mühendisliği",
    ],
    data: {
      city: "Varşova",
      world_rank: "1001-1200",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://www.sggw.edu.pl/en/",
  },
  {
    name: "Varşova Medikal Üniversitesi",
    img: "/assets/uni/varsova-medikal-universitesi.jpg",
    city: "Varşova",
    desc: "Polonya'daki en eski tıp fakültelerinden biridir. Üniversite 200 yılı aşkın bir süredir tıp ve eczacılık alanlarında eğitim vermektedir.",
    all_programs: [
      "Tıp",
      "Diş Hekimliği",
      "Eczacılık",
      "Biyomedikal Bilimler",
      "Fizyoterapi",
      "Hemşirelik",
      "Ergoterapi",
      "Sağlık Bilgi Bilimleri",
      "Biyomedikal Mühendislik",
    ],
    data: {
      city: "Varşova",
      world_rank: "401-450",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://www.wum.edu.pl/en",
  },
  {
    name: "Varşova Güzel Sanatlar Akademisi",
    img: "/assets/uni/varsova-guzel-sanatlar-universitesi.jpg",
    city: "Varşova",
    desc: "Akademide 1500'den fazla öğrenci ve 300'den fazla akademik öğretmen bulunmaktadır. Profesörlerin çoğu kendi alanlarında seçkin sanatçılardır.",
    all_programs: [
      "Ressamlık",
      "Heykeltraş",
      "Grafik Tasarımı",
      "Endüstriyel Tasarım",
      "Film Yapım",
      "Animasyon",
      "Sanat Tarihi",
      "Sanat Teorisi",
      "Eserlerin Korunması ve Restorasyonu",
      "Mimari Anıtların Restorasyonu",
    ],
    data: {
      city: "Varşova",
      world_rank: "700",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://en.asp.waw.pl/en/",
  },
  {
    name: "Chopin Müzik Üniversitesi",
    img: "/assets/uni/chopin-muzik-universitesi.jpg",
    city: "Varşova",
    desc: "Avrupa'nın en eski ve en büyük yüksek müzik eğitimi kurumlarından biridir ve dünyanın en önemli sanat merkezleriyle sürekli işbirliği geliştirmektedir.",
    all_programs: [
      "Piyano",
      "Org",
      "Arpa",
      "Gitar",
      "Vokal",
      "Şeflik",
      "Bestecilik",
      "Müzik Teorisi",
      "Müzik Eğitimi",
      "Etnomüzikoloji",
    ],
    data: {
      city: "Varşova",
      world_rank: "51-100",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://chopin.edu.pl/",
  },
  {
    name: "Lazarski Üniversitesi",
    img: "/assets/uni/lazarski-universitesi.jpg",
    city: "Varşova",
    desc: "1993 yılında kurulan üniversite, kısa sürede ülkenin en saygın eğitim kurumlarından biri haline gelmiştir.",
    all_programs: [
      "Avukatlık",
      "İşletme",
      "Uluslararası ilişkiler",
      "İktisat Bilimi",
    ],
    data: {
      city: "Varşova",
      world_rank: "4980",
      languages: ["Lehçe, İngilizce"],
    },
    link: "https://www.lazarski.pl/en",
  },
];
